{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "4ab49f75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['face-0', 'face-1', 'face-2'])\n"
     ]
    }
   ],
   "source": [
    "from typing import Tuple\n",
    "from OCP.gp import gp_Pnt\n",
    "from OCP.BRepMesh import BRepMesh_IncrementalMesh\n",
    "from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeVertex\n",
    "from OCP.TopExp import TopExp_Explorer\n",
    "from OCP.TopoDS import TopoDS, TopoDS_Shape, TopoDS_Edge, TopoDS_Wire, TopoDS_Face, TopoDS_Vertex\n",
    "from OCP.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_REVERSED, TopAbs_INTERNAL\n",
    "from OCP.BRepMesh import BRepMesh_IncrementalMesh\n",
    "from OCP.BRep import BRep_Tool\n",
    "from OCP.TopTools import TopTools_IndexedMapOfShape\n",
    "from OCP.TopLoc import TopLoc_Location\n",
    "import cadquery as cq\n",
    "from cadquery.func import *\n",
    "from cadquery.selectors import *\n",
    "\n",
    "class FeatureExtract(Selector):\n",
    "    def __init__(self, feature):\n",
    "        self.feature = feature\n",
    "\n",
    "    def filter(self, _):\n",
    "        return [self.feature]\n",
    "\n",
    "Triangles = List[Tuple[int, int, int]]\n",
    "\n",
    "class WorkPlaneImpl:\n",
    "    def __init__(self, obj, tolerance: float = 0.1, angular_tolerance: float = 0.1):\n",
    "        self.obj = obj\n",
    "        self.vertice_index_map = TopTools_IndexedMapOfShape()\n",
    "        self.edge_index_map = TopTools_IndexedMapOfShape()\n",
    "        self.faces: dict = {}\n",
    "        self.edges: dict = {} # edges uuid -> [edge1, edge2, ...], edge = [pointi, pointj, ...]\n",
    "        self.wires: dict = {} # wires uuid -> [wire1, wire2, ...], wire = [edgei, edgej, ...]\n",
    "        self.vertices: dict = {}\n",
    "        self._triangulation(tolerance, angular_tolerance)\n",
    "\n",
    "    def _insert_vertex(self, pnt, tag=None):\n",
    "        vertex = BRepBuilderAPI_MakeVertex(pnt).Vertex() if isinstance(pnt, gp_Pnt) else pnt\n",
    "        if (not self.vertice_index_map.Contains(vertex)):\n",
    "            self.vertice_index_map.Add(vertex)\n",
    "            if (tag != None):\n",
    "                self.obj.vertices(FeatureExtract(vertex)).tag(tag)\n",
    "                self.vertices[tag] = self.vertice_index_map.FindIndex(vertex) - 1\n",
    "        return self.vertice_index_map.FindIndex(vertex) - 1 if tag == None else self.vertices[tag]\n",
    "\n",
    "    def _find_vertex(self, vertex):\n",
    "        return self.vertice_index_map.FindIndex(vertex) - 1\n",
    "    \n",
    "    def _insert_edge(self, edge: TopoDS_Edge, vertices_in_edge):\n",
    "        if (not self.edge_index_map.Contains(edge)):\n",
    "            self.edge_index_map.Add(edge)\n",
    "            tag = f\"edge-{len(self.edges)}\"\n",
    "            self.obj.edges(FeatureExtract(edge)).tag(tag)\n",
    "            self.edges[tag] = vertices_in_edge\n",
    "        return self.edge_index_map.FindIndex(edge) - 1\n",
    "    \n",
    "    def _traverseWire(self, wire_ex: any, bt, triangulation, location):\n",
    "        while wire_ex.More():\n",
    "            wire = TopoDS.Wire_s(wire_ex.Current())\n",
    "            if not wire:\n",
    "                wire_ex.Next()\n",
    "                continue\n",
    "            edge_ex = TopExp_Explorer(wire, TopAbs_EDGE)\n",
    "            edges_in_wire = self._traverseEdge(edge_ex, bt, triangulation, location)\n",
    "            tag = f\"wire-{len(self.wires)}\"\n",
    "            self.obj.wires(FeatureExtract(wire)).tag(tag)\n",
    "            self.wires[tag] = edges_in_wire\n",
    "            wire_ex.Next()\n",
    "\n",
    "    def _traverseEdge(self, edge_ex: any, bt, triangulation, location):\n",
    "        edges_in_wire = []\n",
    "        while edge_ex.More():\n",
    "            vertices_in_edge = []\n",
    "            edge = TopoDS.Edge_s(edge_ex.Current())\n",
    "            if not edge:\n",
    "                edge_ex.Next()\n",
    "                continue\n",
    "            poly = bt.PolygonOnTriangulation_s(edge, triangulation, location)\n",
    "            if not poly:\n",
    "                edge_ex.Next()\n",
    "                continue\n",
    "            nb_edge = poly.NbNodes()\n",
    "            for i in range(1, nb_edge + 1):\n",
    "                pnt = triangulation.Node(poly.Node(i)).Transformed(location.Transformation())\n",
    "                vertices_in_edge.append(self._insert_vertex(pnt))\n",
    "            edges_in_wire.append(self._insert_edge(edge, vertices_in_edge))\n",
    "            edge_ex.Next()\n",
    "        return edges_in_wire\n",
    "\n",
    "    def _parse_face(self, face, triangulation, location):\n",
    "        nb_nodes = triangulation.NbNodes()\n",
    "        nb_triangles = triangulation.NbTriangles()\n",
    "        local_index = {}\n",
    "        for i in range(1, nb_nodes + 1):\n",
    "            pnt = triangulation.Node(i).Transformed(location.Transformation())\n",
    "            local_index[i] = self._insert_vertex(pnt)\n",
    "        triangles = []\n",
    "        for i in range(1, nb_triangles + 1):\n",
    "            i1, i2, i3 = triangulation.Triangle(i).Get()\n",
    "            if face.wrapped.Orientation() in (TopAbs_REVERSED, TopAbs_INTERNAL):\n",
    "                i1, i2 = i2, i1\n",
    "            ind1 = local_index[i1]\n",
    "            ind2 = local_index[i2]\n",
    "            ind3 = local_index[i3]\n",
    "            triangles.append((ind1, ind2, ind3))\n",
    "        tag = f\"face-{len(self.faces)}\"\n",
    "        self.obj.faces(FeatureExtract(face)).tag(tag)\n",
    "        self.faces[tag] = triangles\n",
    "    \n",
    "    def _triangulation(self, tolerance: float, angular_tolerance: float):\n",
    "        shape = self.obj.val().wrapped\n",
    "        BRepMesh_IncrementalMesh(shape, tolerance, True, angular_tolerance, True)\n",
    "        bt = BRep_Tool()\n",
    "        for face in self.obj.faces():\n",
    "            location = TopLoc_Location()\n",
    "            triangulation = bt.Triangulation_s(face.wrapped, location)\n",
    "            if not triangulation:\n",
    "                continue\n",
    "            wire_ex = TopExp_Explorer(face.wrapped, TopAbs_WIRE)\n",
    "            self._traverseWire(wire_ex, bt, triangulation, location)\n",
    "            self._parse_face(face, triangulation, location)\n",
    "        \n",
    "        for vertex in self.obj.vertices():\n",
    "            tag = f\"vertex-{len(self.vertices)}\"\n",
    "            self.vertices[tag] = self._insert_vertex(vertex.wrapped)\n",
    "    \n",
    "    @property\n",
    "    def MeshPoints(self):\n",
    "        points = []\n",
    "        for i in range(1, self.vertice_index_map.Extent() + 1):\n",
    "            vertex = TopoDS.Vertex_s(self.vertice_index_map.FindKey(i))\n",
    "            pnt = BRep_Tool.Pnt_s(vertex)\n",
    "            points.append((pnt.X(), pnt.Y(), pnt.Z()))\n",
    "        return points\n",
    "    @property\n",
    "    def Vertices(self):\n",
    "        return self.vertices\n",
    "    @property\n",
    "    def Edges(self):\n",
    "        return self.edges\n",
    "    @property\n",
    "    def Wires(self):\n",
    "        return self.wires\n",
    "    @property\n",
    "    def Faces(self):\n",
    "        return self.faces\n",
    "    def GetFeature(self, type: str,tag: str):\n",
    "        return self.obj\n",
    "\n",
    "box = cq.Workplane(\"XZ\").circle(2.0).extrude(100)\n",
    "object_box = WorkPlaneImpl(box, 0.1, 0.1)\n",
    "# for i in object_box.Vertices.values():\n",
    "#     print(object_box.MeshPoints[i])\n",
    "print(object_box.Faces.keys())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "70345d02",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_object = object_box.obj.faces(None, 'face-1').workplane().hole(0.11)\n",
    "new_object = new_object.faces(None, 'face-2').circle(3.0).extrude(10)\n",
    "new_object.exportSvg(\"./test.svg\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "afc2eeae",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ast\n",
    "import types\n",
    "\n",
    "class CodeExecutor:\n",
    "    def __init__(self):\n",
    "        self.workplanes = {}\n",
    "        self.sketchs = {}\n",
    "\n",
    "    def LoadFromSource(self, source_code: str):\n",
    "        tree = ast.parse(source_code)\n",
    "        \n",
    "\n",
    "def run_workplanes_from_source(source_code: str):\n",
    "    tree = ast.parse(source_code)\n",
    "    target_func_names = []\n",
    "    for node in tree.body:\n",
    "        if isinstance(node, ast.FunctionDef):\n",
    "            for deco in node.decorator_list:\n",
    "                if isinstance(deco, ast.Name) and deco.id == 'workplane':\n",
    "                    target_func_names.append(node.name)\n",
    "\n",
    "    def workplane(fn): return fn  \n",
    "    mod = types.ModuleType(\"mod\")\n",
    "    mod.__dict__['workplane'] = workplane\n",
    "\n",
    "    # Step 3: 執行整個 source code\n",
    "    exec(source_code, mod.__dict__)\n",
    "\n",
    "    # Step 4: 執行標記過的函數，收集結果\n",
    "    result_dict = {}\n",
    "    for name in target_func_names:\n",
    "        func = getattr(mod, name, None)\n",
    "        if callable(func):\n",
    "            result_dict[name] = func()\n",
    "    return result_dict\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "0df44700",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'cube': 'cube_model', 'cyl': 'cylinder_model'}\n"
     ]
    }
   ],
   "source": [
    "source = '''\n",
    "@workplane\n",
    "def cube():\n",
    "    return \"cube_model\"\n",
    "\n",
    "@workplane\n",
    "def cyl():\n",
    "    return \"cylinder_model\"\n",
    "\n",
    "def not_this_one():\n",
    "    return \"nope\"\n",
    "'''\n",
    "\n",
    "results = run_workplanes_from_source(source)\n",
    "print(results)\n",
    "# 👉 {'cube': 'cube_model', 'cyl': 'cylinder_model'}\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "oasis",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
